#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
#  RectoBase – VPS Initial Setup (Ubuntu 22.04 / 24.04)
#
#  Usage (domain & email wajib, sisanya sudah terisi):
#    bash vps-setup.sh base.rectoversomedia.com admin@rectoverso.com
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail
IFS=$'\n\t'

# ── Tripay credentials (sudah terisi) ────────────────────────────────────────
TRIPAY_API_KEY="${TRIPAY_API_KEY:-YCLYXMbyJHAZxKrVNacBplaZGAvfHatSGZDG0tla}"
TRIPAY_PRIVATE_KEY="${TRIPAY_PRIVATE_KEY:-EZ0yL-IvhEb-nAhCw-bJYAe-3zRU5}"
TRIPAY_MERCHANT_CODE="${TRIPAY_MERCHANT_CODE:-T50630}"

# ── Args ─────────────────────────────────────────────────────────────────────
DOMAIN="${1:?Usage: $0 domain.com email@example.com}"
EMAIL="${2:?Usage: $0 domain.com email@example.com}"
TRIPAY_MODE="production"
for arg in "$@"; do
  case "$arg" in
    --tripay-mode=*) TRIPAY_MODE="${arg#*=}" ;;
    --sandbox)       TRIPAY_MODE="sandbox" ;;
  esac
done

WEBROOT="/var/www/rectobase"
SECRETS_DIR="/etc/rectobase"
SECRETS_FILE="$SECRETS_DIR/tripay.conf"

# ── Colour helpers ────────────────────────────────────────────────────────────
GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; RESET='\033[0m'
step()  { echo -e "\n${GREEN}▶ $*${RESET}"; }
warn()  { echo -e "${YELLOW}⚠  $*${RESET}"; }
fatal() { echo -e "${RED}✗  $*${RESET}"; exit 1; }

[[ $EUID -eq 0 ]] || fatal "Run as root: sudo bash $0 $*"

echo -e "\n${GREEN}══════════════════════════════════════════════════"
echo   "  RectoBase VPS Setup"
echo   "  Domain : $DOMAIN"
echo   "  Email  : $EMAIL"
echo   "  Tripay : $TRIPAY_MODE mode"
echo -e "══════════════════════════════════════════════════${RESET}\n"

# ── 1. Tripay credentials ─────────────────────────────────────────────────────
step "Tripay credentials"
echo "  API Key      : ${TRIPAY_API_KEY:0:8}****"
echo "  Private Key  : ${TRIPAY_PRIVATE_KEY:0:6}****"
echo "  Merchant Code: $TRIPAY_MERCHANT_CODE"
echo "  Mode         : $TRIPAY_MODE"

# ── 2. System update ──────────────────────────────────────────────────────────
step "System update"
apt-get update -qq
DEBIAN_FRONTEND=noninteractive apt-get upgrade -y -qq

# ── 3. Install Nginx + PHP-FPM ────────────────────────────────────────────────
step "Installing Nginx + PHP-FPM + curl"
DEBIAN_FRONTEND=noninteractive apt-get install -y -qq nginx php-fpm php-curl

# Enable & start Nginx
systemctl enable nginx
systemctl start nginx

# Detect PHP-FPM service name
PHP_FPM_SERVICE="$(systemctl list-unit-files 'php*-fpm.service' --no-legend \
  | awk '{print $1}' | head -n1)"
[[ -n "$PHP_FPM_SERVICE" ]] || fatal "PHP-FPM service not found after install."

systemctl enable "$PHP_FPM_SERVICE"
systemctl start  "$PHP_FPM_SERVICE"

# Wait for socket to appear (max 10s)
echo -n "  Waiting for PHP-FPM socket"
PHP_FPM_SOCK=""
for i in $(seq 1 10); do
  PHP_FPM_SOCK="$(find /run/php -name 'php*-fpm.sock' 2>/dev/null | head -n1 || true)"
  if [[ -n "$PHP_FPM_SOCK" ]]; then break; fi
  echo -n "."; sleep 1
done
echo ""
[[ -n "$PHP_FPM_SOCK" ]] || fatal "PHP-FPM socket not found at /run/php/. Check: systemctl status $PHP_FPM_SERVICE"
echo "  PHP-FPM socket: $PHP_FPM_SOCK"

# ── 4. Install Certbot ───────────────────────────────────────────────────────
step "Installing Certbot"
DEBIAN_FRONTEND=noninteractive apt-get install -y -qq certbot python3-certbot-nginx

# ── 5. Web root ───────────────────────────────────────────────────────────────
step "Creating web root: $WEBROOT"
mkdir -p "$WEBROOT/api"
chown -R www-data:www-data "$WEBROOT"
chmod -R 755 "$WEBROOT"

# ── 6. Secrets file (Tripay credentials) ─────────────────────────────────────
step "Writing Tripay secrets to $SECRETS_FILE"
mkdir -p "$SECRETS_DIR"
cat > "$SECRETS_FILE" <<EOF
# RectoBase – Tripay fastcgi params
# Edit then run: sudo systemctl reload nginx
fastcgi_param TRIPAY_API_KEY      "$TRIPAY_API_KEY";
fastcgi_param TRIPAY_PRIVATE_KEY  "$TRIPAY_PRIVATE_KEY";
fastcgi_param TRIPAY_MERCHANT_CODE "$TRIPAY_MERCHANT_CODE";
fastcgi_param TRIPAY_MODE         "$TRIPAY_MODE";
EOF
chmod 600 "$SECRETS_FILE"
echo "  Saved (chmod 600)."

# ── 7. Nginx config ───────────────────────────────────────────────────────────
step "Writing Nginx config"
cat > "/etc/nginx/sites-available/rectobase" <<NGINX
# RectoBase — generated by vps-setup.sh
server {
    listen 80;
    listen [::]:80;
    server_name $DOMAIN;
    root $WEBROOT;
    index index.html;

    # ── PHP API (Tripay backend) ──────────────────────────────────────────
    location ~ ^/api/.+\.php\$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:${PHP_FPM_SOCK};

        # Tripay credentials — stored in secrets file (chmod 600)
        include $SECRETS_FILE;

        # Security: only allow our own JS to call this
        add_header X-Robots-Tag "noindex, nofollow" always;
    }

    # ── Deny raw PHP access outside /api ─────────────────────────────────
    location ~ \.php\$ { deny all; }

    # ── SPA fallback (all routes → index.html) ───────────────────────────
    location / {
        try_files \$uri \$uri/ /index.html;
    }

    # ── Static asset caching ─────────────────────────────────────────────
    location ~* \.(png|jpg|jpeg|gif|ico|svg|webp|woff2?)$ {
        expires 30d;
        add_header Cache-Control "public, immutable";
        access_log off;
    }
    location ~* \.(css|js|json|webmanifest)\$ {
        expires 7d;
        add_header Cache-Control "public, must-revalidate";
        access_log off;
    }

    # ── Gzip ─────────────────────────────────────────────────────────────
    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_min_length 1000;
    gzip_types text/plain text/css application/json application/javascript
               text/xml application/xml image/svg+xml application/manifest+json;

    # ── Security headers ─────────────────────────────────────────────────
    add_header X-Frame-Options        "SAMEORIGIN"               always;
    add_header X-Content-Type-Options "nosniff"                  always;
    add_header Referrer-Policy        "strict-origin-when-cross-origin" always;
    add_header Permissions-Policy     "camera=(), microphone=(), geolocation=()" always;

    server_tokens off;

    # ── Deny dotfiles & log access ───────────────────────────────────────
    location ~ /\.              { deny all; access_log off; }
    location = /api/tripay-callbacks.log { deny all; }
}
NGINX

# Enable site
ln -sf /etc/nginx/sites-available/rectobase /etc/nginx/sites-enabled/rectobase
rm -f /etc/nginx/sites-enabled/default

nginx -t || fatal "Nginx config test failed."
systemctl reload nginx
echo "  Nginx config OK."

# ── 8. Firewall ───────────────────────────────────────────────────────────────
step "Configuring UFW"
ufw --force enable
ufw allow OpenSSH
ufw allow 'Nginx Full'
ufw status numbered

# ── 9. SSL via Certbot ────────────────────────────────────────────────────────
step "Obtaining SSL certificate for $DOMAIN"
certbot --nginx \
  -d "$DOMAIN" \
  --email "$EMAIL" \
  --agree-tos \
  --non-interactive \
  --redirect

systemctl enable certbot.timer 2>/dev/null || true

# ── 10. Health-check ─────────────────────────────────────────────────────────
step "Health check"
sleep 2
HTTP_CODE="$(curl -s -o /dev/null -w '%{http_code}' "https://$DOMAIN/" || echo 000)"
if [[ "$HTTP_CODE" == "200" ]]; then
  echo -e "  ${GREEN}✓ HTTPS returns 200${RESET}"
else
  warn "HTTPS returned $HTTP_CODE — may need a moment to propagate."
fi

PHP_CODE="$(curl -s -o /dev/null -w '%{http_code}' "https://$DOMAIN/api/tripay.php?action=test" || echo 000)"
echo "  PHP endpoint returned HTTP $PHP_CODE"

# ── Done ─────────────────────────────────────────────────────────────────────
echo -e "\n${GREEN}══════════════════════════════════════════════════"
echo   "  ✅  Setup selesai!"
echo   ""
echo   "  Site  : https://$DOMAIN"
echo   "  PHP   : $PHP_FPM_SERVICE"
echo   "  Socket: $PHP_FPM_SOCK"
echo   ""
echo   "  Tripay callback URL (daftarkan di dashboard Tripay):"
echo   "  https://$DOMAIN/api/tripay.php?action=callback"
echo   ""
echo   "  Untuk update credentials Tripay tanpa re-setup:"
echo   "    bash setup-tripay.sh --api-key KEY --private-key PKEY --merchant-code CODE"
echo   ""
echo   "  Untuk deploy file terbaru dari lokal:"
echo   "    ./deploy.sh root@VPS_IP $DOMAIN"
echo -e "══════════════════════════════════════════════════${RESET}\n"
